### ISSUE TITLE
Plans for releasing eval(scoring) code?

### ISSUE THREAD

**Issue by Kyutinium** [PKU-YuanGroup/Video-Bench#3]
Hi.

I noticed that there is no code that will give me the score before submitting to the leaderboard.
Want to check my scores before submitting it and if it's low, I'll work on it more and resubmit it maybe.

Do you have plans for releasing the video_bench scoring code?

**Comment by BinZhu-ece** [comment]
Hello, as our data is evaluated through multiple-choice questions, in order to ensure the fairness of the test results, **we only support submitting and obtaining the final score through the leaderboard.** You can view your score results on the leaderboard and update your ranking results through resubmission

**Comment by Kyutinium** [comment]
Okay. Thank you.
